// Official Codenames word list (400 words from original + duet editions)
export const CODENAMES_WORDS: string[] = [
  // Original Codenames words
  "AFRICA", "AGENT", "AIR", "ALIEN", "ALPS", "AMAZON", "AMBULANCE", "AMERICA",
  "ANGEL", "ANTARCTICA", "APPLE", "ARM", "ATLANTIS", "AUSTRALIA", "AZTEC",
  "BACK", "BALL", "BAND", "BANK", "BAR", "BARK", "BAT", "BATTERY", "BEACH",
  "BEAR", "BEAT", "BED", "BEIJING", "BELL", "BELT", "BERLIN", "BERMUDA",
  "BERRY", "BILL", "BLOCK", "BOARD", "BOLT", "BOMB", "BOND", "BOOM", "BOOT",
  "BOTTLE", "BOW", "BOX", "BRIDGE", "BRUSH", "BUCK", "BUFFALO", "BUG",
  "BUGLE", "BUTTON", "CALF", "CANADA", "CAP", "CAPITAL", "CAR", "CARD",
  "CARROT", "CASINO", "CAST", "CAT", "CELL", "CENTAUR", "CENTER", "CHAIR",
  "CHANGE", "CHARGE", "CHECK", "CHEST", "CHICK", "CHINA", "CHOCOLATE",
  "CHURCH", "CIRCLE", "CLIFF", "CLOAK", "CLOCK", "CLOUD", "CLOWN", "CLUB",
  "COACH", "COAL", "COAT", "CODE", "COLD", "COMIC", "COMPOUND", "CONCERT",
  "CONDUCTOR", "CONTRACT", "COOK", "COPPER", "COTTON", "COURT", "COVER",
  "CRANE", "CRASH", "CRICKET", "CROSS", "CROWN", "CYCLE", "CZECH",
  "DANCE", "DATE", "DAY", "DEATH", "DECK", "DEGREE", "DIAMOND", "DICE",
  "DINOSAUR", "DISEASE", "DOCTOR", "DOG", "DOLLAR", "DOLPHIN", "DRAFT",
  "DRAGON", "DRESS", "DRILL", "DROP", "DRUG", "DRUM", "DUCK", "DWARF",
  "EAGLE", "EGYPT", "EMBASSY", "ENGINE", "ENGLAND", "EUROPE", "EYE",
  "FACE", "FAIR", "FALL", "FAN", "FENCE", "FIELD", "FIGHTER", "FIGURE",
  "FILE", "FILM", "FIRE", "FISH", "FLUTE", "FLY", "FOOT", "FORCE", "FOREST",
  "FORK", "FRANCE", "GAME", "GAS", "GENIUS", "GERMANY", "GHOST", "GIANT",
  "GLASS", "GLOVE", "GOLD", "GRACE", "GRASS", "GREECE", "GREEN", "GROUND",
  "HAM", "HAND", "HANDLE", "HANG", "HAWK", "HEAD", "HEART", "HELICOPTER",
  "HIMALAYAS", "HOLE", "HOLLYWOOD", "HONEY", "HOOD", "HOOK", "HORN", "HORSE",
  "HORSESHOE", "HOSPITAL", "HOTEL", "ICE", "ICE CREAM", "INDIA", "IRON",
  "IVORY", "JACK", "JAM", "JET", "JUPITER", "KANGAROO", "KETCHUP", "KEY",
  "KID", "KING", "KIWI", "KNIFE", "KNIGHT", "LAB", "LAP", "LASER", "LAWYER",
  "LEAD", "LEMON", "LEPRECHAUN", "LIFE", "LIGHT", "LIMOUSINE", "LINE",
  "LINK", "LION", "LITTER", "LOCH NESS", "LOCK", "LOG", "LONDON", "LUCK",
  "MAIL", "MAMMOTH", "MAPLE", "MARBLE", "MARCH", "MARK", "MASS", "MATCH",
  "MERCURY", "MEXICO", "MICROSCOPE", "MILLIONAIRE", "MINE", "MINT", "MISSILE",
  "MODEL", "MOLE", "MOON", "MOSCOW", "MOUNT", "MOUSE", "MOUTH", "MUG",
  "NAIL", "NEEDLE", "NET", "NEW YORK", "NIGHT", "NINJA", "NOTE", "NOVEL",
  "NURSE", "NUT", "OCTOPUS", "OIL", "OLIVE", "OLYMPUS", "OPERA", "ORANGE",
  "ORGAN", "PALM", "PAN", "PANTS", "PAPER", "PARACHUTE", "PARK", "PART",
  "PASS", "PASTE", "PENGUIN", "PHOENIX", "PIANO", "PIE", "PILOT", "PIN",
  "PIPE", "PIRATE", "PISTOL", "PIT", "PITCH", "PLANE", "PLASTIC", "PLATE",
  "PLATYPUS", "PLAY", "PLOT", "POINT", "POISON", "POLE", "POLICE", "POOL",
  "PORT", "POST", "POUND", "PRESS", "PRINCE", "PRINCESS", "PUMPKIN", "PUPIL",
  "PYRAMID", "QUEEN", "RABBIT", "RACKET", "RAY", "REVOLUTION", "RING",
  "ROBOT", "ROCK", "ROME", "ROOT", "ROSE", "ROULETTE", "ROUND", "ROW",
  "RULER", "SATELLITE", "SATURN", "SCALE", "SCHOOL", "SCIENTIST", "SCORPION",
  "SCREEN", "SCUBA DIVER", "SEAL", "SERVER", "SHADOW", "SHAKESPEARE", "SHARK",
  "SHED", "SHELL", "SHIP", "SHOE", "SHOP", "SHOT", "SHOULDER", "SINK",
  "SKYSCRAPER", "SLIP", "SLUG", "SMUGGLER", "SNOW", "SNOWMAN", "SOCK",
  "SOLDIER", "SOUL", "SOUND", "SPACE", "SPELL", "SPIDER", "SPIKE", "SPINE",
  "SPOT", "SPRING", "SPY", "SQUARE", "STADIUM", "STAFF", "STAR", "STATE",
  "STICK", "STOCK", "STRAW", "STREAM", "STRIKE", "STRING", "SUB", "SUIT",
  "SUPERHERO", "SWING", "SWITCH", "TABLE", "TABLET", "TAG", "TAIL", "TAP",
  "TEACHER", "TELESCOPE", "TEMPLE", "THIEF", "THUMB", "TICK", "TIE", "TIME",
  "TOKYO", "TOOTH", "TORCH", "TOWER", "TRACK", "TRAIN", "TRIANGLE", "TRIP",
  "TRUNK", "TUBE", "TURKEY", "UNDERTAKER", "UNICORN", "VACUUM", "VAN", "VET",
  "WAKE", "WALL", "WAR", "WASHER", "WASHINGTON", "WATCH", "WATER", "WAVE",
  "WEB", "WELL", "WHALE", "WHIP", "WIND", "WITCH", "WORM", "YARD",
  // Codenames Duet words
  "ACCIDENT", "ACORN", "ACTOR", "ALARM", "ALBUM", "ALLEY", "ANCHOR", "ANT",
  "APARTMENT", "ARCH", "ARROW", "ASTRONAUT", "ATTIC", "AVOCADO", "BACON",
  "BADGE", "BAGEL", "BAGUETTE", "BALCONY", "BALLOON", "BANANA", "BANDAGE",
  "BANJO", "BARBECUE", "BARN", "BARREL", "BASEMENT", "BASKET", "BATHROOM",
  "BATHTUB", "BEACON", "BEAD", "BEAN", "BEARD", "BEAVER", "BEDROOM", "BEEHIVE",
  "BEET", "BEGGAR", "BENCH", "BICYCLE", "BILLBOARD", "BINGO", "BINOCULARS",
  "BIRD", "BIRTHDAY", "BISCUIT", "BISHOP", "BLANKET", "BLENDER", "BLIMP",
  "BLIZZARD", "BLOOD", "BLUEBERRY", "BLUEPRINT", "BOAT", "BOBSLED", "BONFIRE",
  "BOOK", "BOOKSHELF", "BOOMERANG", "BOUQUET", "BOWLING", "BRACELET", "BRAIN",
  "BREAD", "BREAKFAST", "BRICK", "BRIEFCASE", "BROCCOLI", "BROOM", "BROWNIE",
  "BUBBLE", "BUCKET", "BUFFET", "BULLDOZER", "BULLET", "BUMPER", "BUNNY",
  "BURGER", "BURRITO", "BUS", "BUSH", "BUTTER", "BUTTERFLY", "CABIN", "CABINET",
  "CABLE", "CACTUS", "CAGE", "CAKE", "CALENDAR", "CAMEL", "CAMERA", "CAMPFIRE",
  "CANDLE", "CANDY", "CANOE", "CANYON", "CAPE", "CAPTAIN", "CARDBOARD", "CARGO",
  "CARNIVAL", "CARPET", "CASTLE", "CATERPILLAR", "CAVE", "CEILING", "CELLAR",
  "CEMETERY", "CEREAL", "CHAIN", "CHALK", "CHANDELIER", "CHANNEL", "CHAPEL",
  "CHAPTER", "CHARCOAL", "CHEESE", "CHERRY", "CHICKEN", "CHIMNEY", "CHIP",
  "CIGAR", "CINEMA", "CIRCUS", "CLAY", "CLEANER", "CLINIC", "CLOSET", "CLOTH",
  "COASTER", "COBRA", "COCOA", "COCONUT", "COFFEE", "COIN", "COLLAR", "COLLEGE",
  "COMET", "COMPASS", "COMPUTER", "CONE", "COOKIE", "CORAL", "CORD", "CORK",
  "CORN", "CORNER", "COUCH", "COUNTER", "COUNTRY", "COUPLE", "COUSIN", "COWBOY",
  "CRAB", "CRACKER", "CRADLE", "CRAYON", "CREAM", "CREEK", "CRIB", "CROCODILE"
];

// Function to get random words for a game (Fisher-Yates shuffle for uniform distribution)
export function getRandomWords(count: number = 25): string[] {
  const words = [...CODENAMES_WORDS];
  // Fisher-Yates shuffle
  for (let i = words.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [words[i], words[j]] = [words[j], words[i]];
  }
  // Deduplicate just in case
  const unique = [...new Set(words)];
  return unique.slice(0, count);
}
